Select entreprise demarches
betagouv/signup-front pull request #150
Opened 2020-11-20 10:40 UTC by rdubigny

2020-11-20 10:47 UTC, rdubigny commented
![](https://github.trello.services/images/mini-trello-icon.png) [sur le formulaire API Entreprise, ajouter une partie cas d'usage](https://trello.com/c/v9HLCb8x/799-sur-le-formulaire-api-entreprise-ajouter-une-partie-cas-dusage)

2020-11-26 14:30 UTC, XavierJp approved these changes
Simpler

2020-11-26 15:04 UTC, XavierJp requested changes

2020-11-26 15:09 UTC, XavierJp commented on src/components/form-sections/DemarcheSection/index.js
> +    enrollment: { id, demarche: selectedDemarcheId },
Actually id => enrollmentId and demarche => demarcheId

2020-11-26 15:19 UTC, XavierJp approved these changes

2020-11-26 15:20 UTC, merged