Demarche select validateur
betagouv/signup-front pull request #156
Opened 2020-12-04 17:25 UTC by XavierJp

A merger avec modération

2020-12-08 15:17 UTC, rdubigny requested changes

2020-12-08 15:21 UTC, XavierJp commented on src/components/ConfirmationModal.js
> +const ConfirmationModal = ({
Great but be careful as they are quite different (in term of CTA colour and behaviour)

2020-12-08 15:22 UTC, XavierJp commented on src/components/form-sections/DemarcheSection/DemarcheSectionReadOnly.js
> +  const [modifiedFields, setModifiedFields] = useState(false);
haha I definitely agree with you !

2020-12-08 15:25 UTC, XavierJp commented on src/components/form-sections/DemarcheSection/DemarcheSectionSelect.js
> +    // this is not great but state update goes like this
My bad

2020-12-08 15:29 UTC, XavierJp commented on src/components/form-sections/DemarcheSection/DemarcheSectionSelect.js
> +      <DemarcheSectionSelectNotification
oh oh tricky one :)

2020-12-09 09:01 UTC, rdubigny requested changes

2020-12-09 09:01 UTC, rdubigny commented on src/components/form-sections/DemarcheSection/DemarcheSectionSelectNotification.js
> +    Object.keys(demarches).indexOf(selectedDemarcheId) > -1 &&
This is quite known syntax for js dev but I find it hackish, what about lodash `has`:

`has(demarches, selectedDemarcheId)`

2020-12-09 09:03 UTC, rdubigny commented on src/components/ConfirmationModal.js
> +const ConfirmationModal = ({
Duly noted. I'll keep this conversation un-resolved to remind me to do it.

2020-12-10 10:41 UTC, merged